// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToolManagementSystem.Shared.Data;

namespace ToolManagementSystem.Client.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200820095919_sr5")]
    partial class sr5
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ToolManagementSystem.Shared.Models.EmployeeRoles", b =>
                {
                    b.Property<int>("EmployeeRolesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("EmployeesIdId")
                        .HasColumnType("int");

                    b.Property<int?>("RolesId1")
                        .HasColumnType("int");

                    b.HasKey("EmployeeRolesId");

                    b.HasIndex("EmployeesIdId");

                    b.HasIndex("RolesId1");

                    b.ToTable("EmployeeRoles");
                });

            modelBuilder.Entity("ToolManagementSystem.Shared.Models.Employees", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Patronymic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Question")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("ToolManagementSystem.Shared.Models.Pages", b =>
                {
                    b.Property<int>("PageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NamePage")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PageId");

                    b.ToTable("Pages");
                });

            modelBuilder.Entity("ToolManagementSystem.Shared.Models.Roles", b =>
                {
                    b.Property<int>("RolesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("RoleName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RolesId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("ToolManagementSystem.Shared.Models.RolesPages", b =>
                {
                    b.Property<int>("RolesPagesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<int?>("PagesIdPageId")
                        .HasColumnType("int");

                    b.Property<int?>("RolesId1")
                        .HasColumnType("int");

                    b.HasKey("RolesPagesId");

                    b.HasIndex("PagesIdPageId");

                    b.HasIndex("RolesId1");

                    b.ToTable("RolesPages");
                });

            modelBuilder.Entity("ToolManagementSystem.Shared.Models.EmployeeRoles", b =>
                {
                    b.HasOne("ToolManagementSystem.Shared.Models.Employees", "EmployeesId")
                        .WithMany()
                        .HasForeignKey("EmployeesIdId");

                    b.HasOne("ToolManagementSystem.Shared.Models.Roles", "RolesId")
                        .WithMany()
                        .HasForeignKey("RolesId1");
                });

            modelBuilder.Entity("ToolManagementSystem.Shared.Models.RolesPages", b =>
                {
                    b.HasOne("ToolManagementSystem.Shared.Models.Pages", "PagesId")
                        .WithMany()
                        .HasForeignKey("PagesIdPageId");

                    b.HasOne("ToolManagementSystem.Shared.Models.Roles", "RolesId")
                        .WithMany()
                        .HasForeignKey("RolesId1");
                });
#pragma warning restore 612, 618
        }
    }
}
